// Code generated by ent, DO NOT EDIT.

package usagelogdetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the usagelogdetail type in the database.
	Label = "usage_log_detail"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsageLogID holds the string denoting the usage_log_id field in the database.
	FieldUsageLogID = "usage_log_id"
	// FieldRequestPayloadJSON holds the string denoting the request_payload_json field in the database.
	FieldRequestPayloadJSON = "request_payload_json"
	// FieldResponsePayloadJSON holds the string denoting the response_payload_json field in the database.
	FieldResponsePayloadJSON = "response_payload_json"
	// FieldCompressedRequestPayloadJSON holds the string denoting the compressed_request_payload_json field in the database.
	FieldCompressedRequestPayloadJSON = "compressed_request_payload_json"
	// FieldCompressedResponsePayloadJSON holds the string denoting the compressed_response_payload_json field in the database.
	FieldCompressedResponsePayloadJSON = "compressed_response_payload_json"
	// FieldRequestPayloadBytes holds the string denoting the request_payload_bytes field in the database.
	FieldRequestPayloadBytes = "request_payload_bytes"
	// FieldResponsePayloadBytes holds the string denoting the response_payload_bytes field in the database.
	FieldResponsePayloadBytes = "response_payload_bytes"
	// FieldRequestTruncated holds the string denoting the request_truncated field in the database.
	FieldRequestTruncated = "request_truncated"
	// FieldResponseTruncated holds the string denoting the response_truncated field in the database.
	FieldResponseTruncated = "response_truncated"
	// FieldFullPayloadsCleanedAt holds the string denoting the full_payloads_cleaned_at field in the database.
	FieldFullPayloadsCleanedAt = "full_payloads_cleaned_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUsageLog holds the string denoting the usage_log edge name in mutations.
	EdgeUsageLog = "usage_log"
	// Table holds the table name of the usagelogdetail in the database.
	Table = "usage_log_details"
	// UsageLogTable is the table that holds the usage_log relation/edge.
	UsageLogTable = "usage_log_details"
	// UsageLogInverseTable is the table name for the UsageLog entity.
	// It exists in this package in order to avoid circular dependency with the "usagelog" package.
	UsageLogInverseTable = "usage_logs"
	// UsageLogColumn is the table column denoting the usage_log relation/edge.
	UsageLogColumn = "usage_log_id"
)

// Columns holds all SQL columns for usagelogdetail fields.
var Columns = []string{
	FieldID,
	FieldUsageLogID,
	FieldRequestPayloadJSON,
	FieldResponsePayloadJSON,
	FieldCompressedRequestPayloadJSON,
	FieldCompressedResponsePayloadJSON,
	FieldRequestPayloadBytes,
	FieldResponsePayloadBytes,
	FieldRequestTruncated,
	FieldResponseTruncated,
	FieldFullPayloadsCleanedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRequestTruncated holds the default value on creation for the "request_truncated" field.
	DefaultRequestTruncated bool
	// DefaultResponseTruncated holds the default value on creation for the "response_truncated" field.
	DefaultResponseTruncated bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UsageLogDetail queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsageLogID orders the results by the usage_log_id field.
func ByUsageLogID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageLogID, opts...).ToFunc()
}

// ByRequestPayloadJSON orders the results by the request_payload_json field.
func ByRequestPayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestPayloadJSON, opts...).ToFunc()
}

// ByResponsePayloadJSON orders the results by the response_payload_json field.
func ByResponsePayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponsePayloadJSON, opts...).ToFunc()
}

// ByCompressedRequestPayloadJSON orders the results by the compressed_request_payload_json field.
func ByCompressedRequestPayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompressedRequestPayloadJSON, opts...).ToFunc()
}

// ByCompressedResponsePayloadJSON orders the results by the compressed_response_payload_json field.
func ByCompressedResponsePayloadJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompressedResponsePayloadJSON, opts...).ToFunc()
}

// ByRequestPayloadBytes orders the results by the request_payload_bytes field.
func ByRequestPayloadBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestPayloadBytes, opts...).ToFunc()
}

// ByResponsePayloadBytes orders the results by the response_payload_bytes field.
func ByResponsePayloadBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponsePayloadBytes, opts...).ToFunc()
}

// ByRequestTruncated orders the results by the request_truncated field.
func ByRequestTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestTruncated, opts...).ToFunc()
}

// ByResponseTruncated orders the results by the response_truncated field.
func ByResponseTruncated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseTruncated, opts...).ToFunc()
}

// ByFullPayloadsCleanedAt orders the results by the full_payloads_cleaned_at field.
func ByFullPayloadsCleanedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullPayloadsCleanedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsageLogField orders the results by usage_log field.
func ByUsageLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsageLogStep(), sql.OrderByField(field, opts...))
	}
}
func newUsageLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsageLogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
	)
}
