// Code generated by ent, DO NOT EDIT.

package usagelogdetail

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldID, id))
}

// UsageLogID applies equality check predicate on the "usage_log_id" field. It's identical to UsageLogIDEQ.
func UsageLogID(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUsageLogID, v))
}

// RequestPayloadJSON applies equality check predicate on the "request_payload_json" field. It's identical to RequestPayloadJSONEQ.
func RequestPayloadJSON(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestPayloadJSON, v))
}

// ResponsePayloadJSON applies equality check predicate on the "response_payload_json" field. It's identical to ResponsePayloadJSONEQ.
func ResponsePayloadJSON(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponsePayloadJSON, v))
}

// RequestPayloadBytes applies equality check predicate on the "request_payload_bytes" field. It's identical to RequestPayloadBytesEQ.
func RequestPayloadBytes(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestPayloadBytes, v))
}

// ResponsePayloadBytes applies equality check predicate on the "response_payload_bytes" field. It's identical to ResponsePayloadBytesEQ.
func ResponsePayloadBytes(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponsePayloadBytes, v))
}

// RequestTruncated applies equality check predicate on the "request_truncated" field. It's identical to RequestTruncatedEQ.
func RequestTruncated(v bool) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestTruncated, v))
}

// ResponseTruncated applies equality check predicate on the "response_truncated" field. It's identical to ResponseTruncatedEQ.
func ResponseTruncated(v bool) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseTruncated, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// UsageLogIDEQ applies the EQ predicate on the "usage_log_id" field.
func UsageLogIDEQ(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUsageLogID, v))
}

// UsageLogIDNEQ applies the NEQ predicate on the "usage_log_id" field.
func UsageLogIDNEQ(v int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUsageLogID, v))
}

// UsageLogIDIn applies the In predicate on the "usage_log_id" field.
func UsageLogIDIn(vs ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUsageLogID, vs...))
}

// UsageLogIDNotIn applies the NotIn predicate on the "usage_log_id" field.
func UsageLogIDNotIn(vs ...int64) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUsageLogID, vs...))
}

// RequestPayloadJSONEQ applies the EQ predicate on the "request_payload_json" field.
func RequestPayloadJSONEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONNEQ applies the NEQ predicate on the "request_payload_json" field.
func RequestPayloadJSONNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONIn applies the In predicate on the "request_payload_json" field.
func RequestPayloadJSONIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldRequestPayloadJSON, vs...))
}

// RequestPayloadJSONNotIn applies the NotIn predicate on the "request_payload_json" field.
func RequestPayloadJSONNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldRequestPayloadJSON, vs...))
}

// RequestPayloadJSONGT applies the GT predicate on the "request_payload_json" field.
func RequestPayloadJSONGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONGTE applies the GTE predicate on the "request_payload_json" field.
func RequestPayloadJSONGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONLT applies the LT predicate on the "request_payload_json" field.
func RequestPayloadJSONLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONLTE applies the LTE predicate on the "request_payload_json" field.
func RequestPayloadJSONLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONContains applies the Contains predicate on the "request_payload_json" field.
func RequestPayloadJSONContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONHasPrefix applies the HasPrefix predicate on the "request_payload_json" field.
func RequestPayloadJSONHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONHasSuffix applies the HasSuffix predicate on the "request_payload_json" field.
func RequestPayloadJSONHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONIsNil applies the IsNil predicate on the "request_payload_json" field.
func RequestPayloadJSONIsNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIsNull(FieldRequestPayloadJSON))
}

// RequestPayloadJSONNotNil applies the NotNil predicate on the "request_payload_json" field.
func RequestPayloadJSONNotNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotNull(FieldRequestPayloadJSON))
}

// RequestPayloadJSONEqualFold applies the EqualFold predicate on the "request_payload_json" field.
func RequestPayloadJSONEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldRequestPayloadJSON, v))
}

// RequestPayloadJSONContainsFold applies the ContainsFold predicate on the "request_payload_json" field.
func RequestPayloadJSONContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldRequestPayloadJSON, v))
}

// ResponsePayloadJSONEQ applies the EQ predicate on the "response_payload_json" field.
func ResponsePayloadJSONEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONNEQ applies the NEQ predicate on the "response_payload_json" field.
func ResponsePayloadJSONNEQ(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONIn applies the In predicate on the "response_payload_json" field.
func ResponsePayloadJSONIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldResponsePayloadJSON, vs...))
}

// ResponsePayloadJSONNotIn applies the NotIn predicate on the "response_payload_json" field.
func ResponsePayloadJSONNotIn(vs ...string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldResponsePayloadJSON, vs...))
}

// ResponsePayloadJSONGT applies the GT predicate on the "response_payload_json" field.
func ResponsePayloadJSONGT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONGTE applies the GTE predicate on the "response_payload_json" field.
func ResponsePayloadJSONGTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONLT applies the LT predicate on the "response_payload_json" field.
func ResponsePayloadJSONLT(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONLTE applies the LTE predicate on the "response_payload_json" field.
func ResponsePayloadJSONLTE(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONContains applies the Contains predicate on the "response_payload_json" field.
func ResponsePayloadJSONContains(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContains(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONHasPrefix applies the HasPrefix predicate on the "response_payload_json" field.
func ResponsePayloadJSONHasPrefix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasPrefix(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONHasSuffix applies the HasSuffix predicate on the "response_payload_json" field.
func ResponsePayloadJSONHasSuffix(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldHasSuffix(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONIsNil applies the IsNil predicate on the "response_payload_json" field.
func ResponsePayloadJSONIsNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIsNull(FieldResponsePayloadJSON))
}

// ResponsePayloadJSONNotNil applies the NotNil predicate on the "response_payload_json" field.
func ResponsePayloadJSONNotNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotNull(FieldResponsePayloadJSON))
}

// ResponsePayloadJSONEqualFold applies the EqualFold predicate on the "response_payload_json" field.
func ResponsePayloadJSONEqualFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEqualFold(FieldResponsePayloadJSON, v))
}

// ResponsePayloadJSONContainsFold applies the ContainsFold predicate on the "response_payload_json" field.
func ResponsePayloadJSONContainsFold(v string) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldContainsFold(FieldResponsePayloadJSON, v))
}

// RequestPayloadBytesEQ applies the EQ predicate on the "request_payload_bytes" field.
func RequestPayloadBytesEQ(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestPayloadBytes, v))
}

// RequestPayloadBytesNEQ applies the NEQ predicate on the "request_payload_bytes" field.
func RequestPayloadBytesNEQ(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldRequestPayloadBytes, v))
}

// RequestPayloadBytesIn applies the In predicate on the "request_payload_bytes" field.
func RequestPayloadBytesIn(vs ...int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldRequestPayloadBytes, vs...))
}

// RequestPayloadBytesNotIn applies the NotIn predicate on the "request_payload_bytes" field.
func RequestPayloadBytesNotIn(vs ...int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldRequestPayloadBytes, vs...))
}

// RequestPayloadBytesGT applies the GT predicate on the "request_payload_bytes" field.
func RequestPayloadBytesGT(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldRequestPayloadBytes, v))
}

// RequestPayloadBytesGTE applies the GTE predicate on the "request_payload_bytes" field.
func RequestPayloadBytesGTE(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldRequestPayloadBytes, v))
}

// RequestPayloadBytesLT applies the LT predicate on the "request_payload_bytes" field.
func RequestPayloadBytesLT(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldRequestPayloadBytes, v))
}

// RequestPayloadBytesLTE applies the LTE predicate on the "request_payload_bytes" field.
func RequestPayloadBytesLTE(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldRequestPayloadBytes, v))
}

// RequestPayloadBytesIsNil applies the IsNil predicate on the "request_payload_bytes" field.
func RequestPayloadBytesIsNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIsNull(FieldRequestPayloadBytes))
}

// RequestPayloadBytesNotNil applies the NotNil predicate on the "request_payload_bytes" field.
func RequestPayloadBytesNotNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotNull(FieldRequestPayloadBytes))
}

// ResponsePayloadBytesEQ applies the EQ predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesEQ(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponsePayloadBytes, v))
}

// ResponsePayloadBytesNEQ applies the NEQ predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesNEQ(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldResponsePayloadBytes, v))
}

// ResponsePayloadBytesIn applies the In predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesIn(vs ...int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldResponsePayloadBytes, vs...))
}

// ResponsePayloadBytesNotIn applies the NotIn predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesNotIn(vs ...int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldResponsePayloadBytes, vs...))
}

// ResponsePayloadBytesGT applies the GT predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesGT(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldResponsePayloadBytes, v))
}

// ResponsePayloadBytesGTE applies the GTE predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesGTE(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldResponsePayloadBytes, v))
}

// ResponsePayloadBytesLT applies the LT predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesLT(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldResponsePayloadBytes, v))
}

// ResponsePayloadBytesLTE applies the LTE predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesLTE(v int) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldResponsePayloadBytes, v))
}

// ResponsePayloadBytesIsNil applies the IsNil predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesIsNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIsNull(FieldResponsePayloadBytes))
}

// ResponsePayloadBytesNotNil applies the NotNil predicate on the "response_payload_bytes" field.
func ResponsePayloadBytesNotNil() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotNull(FieldResponsePayloadBytes))
}

// RequestTruncatedEQ applies the EQ predicate on the "request_truncated" field.
func RequestTruncatedEQ(v bool) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldRequestTruncated, v))
}

// RequestTruncatedNEQ applies the NEQ predicate on the "request_truncated" field.
func RequestTruncatedNEQ(v bool) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldRequestTruncated, v))
}

// ResponseTruncatedEQ applies the EQ predicate on the "response_truncated" field.
func ResponseTruncatedEQ(v bool) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldResponseTruncated, v))
}

// ResponseTruncatedNEQ applies the NEQ predicate on the "response_truncated" field.
func ResponseTruncatedNEQ(v bool) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldResponseTruncated, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUsageLog applies the HasEdge predicate on the "usage_log" edge.
func HasUsageLog() predicate.UsageLogDetail {
	return predicate.UsageLogDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UsageLogTable, UsageLogColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogWith applies the HasEdge predicate on the "usage_log" edge with a given conditions (other predicates).
func HasUsageLogWith(preds ...predicate.UsageLog) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(func(s *sql.Selector) {
		step := newUsageLogStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UsageLogDetail) predicate.UsageLogDetail {
	return predicate.UsageLogDetail(sql.NotPredicates(p))
}
