// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usagelogdetail"
)

// UsageLogDetailUpdate is the builder for updating UsageLogDetail entities.
type UsageLogDetailUpdate struct {
	config
	hooks    []Hook
	mutation *UsageLogDetailMutation
}

// Where appends a list predicates to the UsageLogDetailUpdate builder.
func (_u *UsageLogDetailUpdate) Where(ps ...predicate.UsageLogDetail) *UsageLogDetailUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageLogDetailUpdate) SetUsageLogID(v int64) *UsageLogDetailUpdate {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableUsageLogID(v *int64) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetRequestPayloadJSON sets the "request_payload_json" field.
func (_u *UsageLogDetailUpdate) SetRequestPayloadJSON(v string) *UsageLogDetailUpdate {
	_u.mutation.SetRequestPayloadJSON(v)
	return _u
}

// SetNillableRequestPayloadJSON sets the "request_payload_json" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableRequestPayloadJSON(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetRequestPayloadJSON(*v)
	}
	return _u
}

// ClearRequestPayloadJSON clears the value of the "request_payload_json" field.
func (_u *UsageLogDetailUpdate) ClearRequestPayloadJSON() *UsageLogDetailUpdate {
	_u.mutation.ClearRequestPayloadJSON()
	return _u
}

// SetResponsePayloadJSON sets the "response_payload_json" field.
func (_u *UsageLogDetailUpdate) SetResponsePayloadJSON(v string) *UsageLogDetailUpdate {
	_u.mutation.SetResponsePayloadJSON(v)
	return _u
}

// SetNillableResponsePayloadJSON sets the "response_payload_json" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableResponsePayloadJSON(v *string) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetResponsePayloadJSON(*v)
	}
	return _u
}

// ClearResponsePayloadJSON clears the value of the "response_payload_json" field.
func (_u *UsageLogDetailUpdate) ClearResponsePayloadJSON() *UsageLogDetailUpdate {
	_u.mutation.ClearResponsePayloadJSON()
	return _u
}

// SetRequestPayloadBytes sets the "request_payload_bytes" field.
func (_u *UsageLogDetailUpdate) SetRequestPayloadBytes(v int) *UsageLogDetailUpdate {
	_u.mutation.ResetRequestPayloadBytes()
	_u.mutation.SetRequestPayloadBytes(v)
	return _u
}

// SetNillableRequestPayloadBytes sets the "request_payload_bytes" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableRequestPayloadBytes(v *int) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetRequestPayloadBytes(*v)
	}
	return _u
}

// AddRequestPayloadBytes adds value to the "request_payload_bytes" field.
func (_u *UsageLogDetailUpdate) AddRequestPayloadBytes(v int) *UsageLogDetailUpdate {
	_u.mutation.AddRequestPayloadBytes(v)
	return _u
}

// ClearRequestPayloadBytes clears the value of the "request_payload_bytes" field.
func (_u *UsageLogDetailUpdate) ClearRequestPayloadBytes() *UsageLogDetailUpdate {
	_u.mutation.ClearRequestPayloadBytes()
	return _u
}

// SetResponsePayloadBytes sets the "response_payload_bytes" field.
func (_u *UsageLogDetailUpdate) SetResponsePayloadBytes(v int) *UsageLogDetailUpdate {
	_u.mutation.ResetResponsePayloadBytes()
	_u.mutation.SetResponsePayloadBytes(v)
	return _u
}

// SetNillableResponsePayloadBytes sets the "response_payload_bytes" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableResponsePayloadBytes(v *int) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetResponsePayloadBytes(*v)
	}
	return _u
}

// AddResponsePayloadBytes adds value to the "response_payload_bytes" field.
func (_u *UsageLogDetailUpdate) AddResponsePayloadBytes(v int) *UsageLogDetailUpdate {
	_u.mutation.AddResponsePayloadBytes(v)
	return _u
}

// ClearResponsePayloadBytes clears the value of the "response_payload_bytes" field.
func (_u *UsageLogDetailUpdate) ClearResponsePayloadBytes() *UsageLogDetailUpdate {
	_u.mutation.ClearResponsePayloadBytes()
	return _u
}

// SetRequestTruncated sets the "request_truncated" field.
func (_u *UsageLogDetailUpdate) SetRequestTruncated(v bool) *UsageLogDetailUpdate {
	_u.mutation.SetRequestTruncated(v)
	return _u
}

// SetNillableRequestTruncated sets the "request_truncated" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableRequestTruncated(v *bool) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetRequestTruncated(*v)
	}
	return _u
}

// SetResponseTruncated sets the "response_truncated" field.
func (_u *UsageLogDetailUpdate) SetResponseTruncated(v bool) *UsageLogDetailUpdate {
	_u.mutation.SetResponseTruncated(v)
	return _u
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_u *UsageLogDetailUpdate) SetNillableResponseTruncated(v *bool) *UsageLogDetailUpdate {
	if v != nil {
		_u.SetResponseTruncated(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageLogDetailUpdate) SetUpdatedAt(v time.Time) *UsageLogDetailUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdate) SetUsageLog(v *UsageLog) *UsageLogDetailUpdate {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the UsageLogDetailMutation object of the builder.
func (_u *UsageLogDetailUpdate) Mutation() *UsageLogDetailMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdate) ClearUsageLog() *UsageLogDetailUpdate {
	_u.mutation.ClearUsageLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageLogDetailUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageLogDetailUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageLogDetailUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageLogDetailUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageLogDetailUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagelogdetail.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageLogDetailUpdate) check() error {
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageLogDetail.usage_log"`)
	}
	return nil
}

func (_u *UsageLogDetailUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagelogdetail.Table, usagelogdetail.Columns, sqlgraph.NewFieldSpec(usagelogdetail.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestPayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldRequestPayloadJSON, field.TypeString, value)
	}
	if _u.mutation.RequestPayloadJSONCleared() {
		_spec.ClearField(usagelogdetail.FieldRequestPayloadJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ResponsePayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldResponsePayloadJSON, field.TypeString, value)
	}
	if _u.mutation.ResponsePayloadJSONCleared() {
		_spec.ClearField(usagelogdetail.FieldResponsePayloadJSON, field.TypeString)
	}
	if value, ok := _u.mutation.RequestPayloadBytes(); ok {
		_spec.SetField(usagelogdetail.FieldRequestPayloadBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestPayloadBytes(); ok {
		_spec.AddField(usagelogdetail.FieldRequestPayloadBytes, field.TypeInt, value)
	}
	if _u.mutation.RequestPayloadBytesCleared() {
		_spec.ClearField(usagelogdetail.FieldRequestPayloadBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponsePayloadBytes(); ok {
		_spec.SetField(usagelogdetail.FieldResponsePayloadBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponsePayloadBytes(); ok {
		_spec.AddField(usagelogdetail.FieldResponsePayloadBytes, field.TypeInt, value)
	}
	if _u.mutation.ResponsePayloadBytesCleared() {
		_spec.ClearField(usagelogdetail.FieldResponsePayloadBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestTruncated(); ok {
		_spec.SetField(usagelogdetail.FieldRequestTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseTruncated(); ok {
		_spec.SetField(usagelogdetail.FieldResponseTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagelogdetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelogdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageLogDetailUpdateOne is the builder for updating a single UsageLogDetail entity.
type UsageLogDetailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageLogDetailMutation
}

// SetUsageLogID sets the "usage_log_id" field.
func (_u *UsageLogDetailUpdateOne) SetUsageLogID(v int64) *UsageLogDetailUpdateOne {
	_u.mutation.SetUsageLogID(v)
	return _u
}

// SetNillableUsageLogID sets the "usage_log_id" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableUsageLogID(v *int64) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetUsageLogID(*v)
	}
	return _u
}

// SetRequestPayloadJSON sets the "request_payload_json" field.
func (_u *UsageLogDetailUpdateOne) SetRequestPayloadJSON(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetRequestPayloadJSON(v)
	return _u
}

// SetNillableRequestPayloadJSON sets the "request_payload_json" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableRequestPayloadJSON(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetRequestPayloadJSON(*v)
	}
	return _u
}

// ClearRequestPayloadJSON clears the value of the "request_payload_json" field.
func (_u *UsageLogDetailUpdateOne) ClearRequestPayloadJSON() *UsageLogDetailUpdateOne {
	_u.mutation.ClearRequestPayloadJSON()
	return _u
}

// SetResponsePayloadJSON sets the "response_payload_json" field.
func (_u *UsageLogDetailUpdateOne) SetResponsePayloadJSON(v string) *UsageLogDetailUpdateOne {
	_u.mutation.SetResponsePayloadJSON(v)
	return _u
}

// SetNillableResponsePayloadJSON sets the "response_payload_json" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableResponsePayloadJSON(v *string) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetResponsePayloadJSON(*v)
	}
	return _u
}

// ClearResponsePayloadJSON clears the value of the "response_payload_json" field.
func (_u *UsageLogDetailUpdateOne) ClearResponsePayloadJSON() *UsageLogDetailUpdateOne {
	_u.mutation.ClearResponsePayloadJSON()
	return _u
}

// SetRequestPayloadBytes sets the "request_payload_bytes" field.
func (_u *UsageLogDetailUpdateOne) SetRequestPayloadBytes(v int) *UsageLogDetailUpdateOne {
	_u.mutation.ResetRequestPayloadBytes()
	_u.mutation.SetRequestPayloadBytes(v)
	return _u
}

// SetNillableRequestPayloadBytes sets the "request_payload_bytes" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableRequestPayloadBytes(v *int) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetRequestPayloadBytes(*v)
	}
	return _u
}

// AddRequestPayloadBytes adds value to the "request_payload_bytes" field.
func (_u *UsageLogDetailUpdateOne) AddRequestPayloadBytes(v int) *UsageLogDetailUpdateOne {
	_u.mutation.AddRequestPayloadBytes(v)
	return _u
}

// ClearRequestPayloadBytes clears the value of the "request_payload_bytes" field.
func (_u *UsageLogDetailUpdateOne) ClearRequestPayloadBytes() *UsageLogDetailUpdateOne {
	_u.mutation.ClearRequestPayloadBytes()
	return _u
}

// SetResponsePayloadBytes sets the "response_payload_bytes" field.
func (_u *UsageLogDetailUpdateOne) SetResponsePayloadBytes(v int) *UsageLogDetailUpdateOne {
	_u.mutation.ResetResponsePayloadBytes()
	_u.mutation.SetResponsePayloadBytes(v)
	return _u
}

// SetNillableResponsePayloadBytes sets the "response_payload_bytes" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableResponsePayloadBytes(v *int) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetResponsePayloadBytes(*v)
	}
	return _u
}

// AddResponsePayloadBytes adds value to the "response_payload_bytes" field.
func (_u *UsageLogDetailUpdateOne) AddResponsePayloadBytes(v int) *UsageLogDetailUpdateOne {
	_u.mutation.AddResponsePayloadBytes(v)
	return _u
}

// ClearResponsePayloadBytes clears the value of the "response_payload_bytes" field.
func (_u *UsageLogDetailUpdateOne) ClearResponsePayloadBytes() *UsageLogDetailUpdateOne {
	_u.mutation.ClearResponsePayloadBytes()
	return _u
}

// SetRequestTruncated sets the "request_truncated" field.
func (_u *UsageLogDetailUpdateOne) SetRequestTruncated(v bool) *UsageLogDetailUpdateOne {
	_u.mutation.SetRequestTruncated(v)
	return _u
}

// SetNillableRequestTruncated sets the "request_truncated" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableRequestTruncated(v *bool) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetRequestTruncated(*v)
	}
	return _u
}

// SetResponseTruncated sets the "response_truncated" field.
func (_u *UsageLogDetailUpdateOne) SetResponseTruncated(v bool) *UsageLogDetailUpdateOne {
	_u.mutation.SetResponseTruncated(v)
	return _u
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_u *UsageLogDetailUpdateOne) SetNillableResponseTruncated(v *bool) *UsageLogDetailUpdateOne {
	if v != nil {
		_u.SetResponseTruncated(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UsageLogDetailUpdateOne) SetUpdatedAt(v time.Time) *UsageLogDetailUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdateOne) SetUsageLog(v *UsageLog) *UsageLogDetailUpdateOne {
	return _u.SetUsageLogID(v.ID)
}

// Mutation returns the UsageLogDetailMutation object of the builder.
func (_u *UsageLogDetailUpdateOne) Mutation() *UsageLogDetailMutation {
	return _u.mutation
}

// ClearUsageLog clears the "usage_log" edge to the UsageLog entity.
func (_u *UsageLogDetailUpdateOne) ClearUsageLog() *UsageLogDetailUpdateOne {
	_u.mutation.ClearUsageLog()
	return _u
}

// Where appends a list predicates to the UsageLogDetailUpdate builder.
func (_u *UsageLogDetailUpdateOne) Where(ps ...predicate.UsageLogDetail) *UsageLogDetailUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageLogDetailUpdateOne) Select(field string, fields ...string) *UsageLogDetailUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageLogDetail entity.
func (_u *UsageLogDetailUpdateOne) Save(ctx context.Context) (*UsageLogDetail, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageLogDetailUpdateOne) SaveX(ctx context.Context) *UsageLogDetail {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageLogDetailUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageLogDetailUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageLogDetailUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := usagelogdetail.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageLogDetailUpdateOne) check() error {
	if _u.mutation.UsageLogCleared() && len(_u.mutation.UsageLogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UsageLogDetail.usage_log"`)
	}
	return nil
}

func (_u *UsageLogDetailUpdateOne) sqlSave(ctx context.Context) (_node *UsageLogDetail, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagelogdetail.Table, usagelogdetail.Columns, sqlgraph.NewFieldSpec(usagelogdetail.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageLogDetail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagelogdetail.FieldID)
		for _, f := range fields {
			if !usagelogdetail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagelogdetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestPayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldRequestPayloadJSON, field.TypeString, value)
	}
	if _u.mutation.RequestPayloadJSONCleared() {
		_spec.ClearField(usagelogdetail.FieldRequestPayloadJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ResponsePayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldResponsePayloadJSON, field.TypeString, value)
	}
	if _u.mutation.ResponsePayloadJSONCleared() {
		_spec.ClearField(usagelogdetail.FieldResponsePayloadJSON, field.TypeString)
	}
	if value, ok := _u.mutation.RequestPayloadBytes(); ok {
		_spec.SetField(usagelogdetail.FieldRequestPayloadBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestPayloadBytes(); ok {
		_spec.AddField(usagelogdetail.FieldRequestPayloadBytes, field.TypeInt, value)
	}
	if _u.mutation.RequestPayloadBytesCleared() {
		_spec.ClearField(usagelogdetail.FieldRequestPayloadBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponsePayloadBytes(); ok {
		_spec.SetField(usagelogdetail.FieldResponsePayloadBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponsePayloadBytes(); ok {
		_spec.AddField(usagelogdetail.FieldResponsePayloadBytes, field.TypeInt, value)
	}
	if _u.mutation.ResponsePayloadBytesCleared() {
		_spec.ClearField(usagelogdetail.FieldResponsePayloadBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestTruncated(); ok {
		_spec.SetField(usagelogdetail.FieldRequestTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ResponseTruncated(); ok {
		_spec.SetField(usagelogdetail.FieldResponseTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(usagelogdetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsageLogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UsageLogDetail{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagelogdetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
