// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usagelogdetail"
)

// UsageLogDetailCreate is the builder for creating a UsageLogDetail entity.
type UsageLogDetailCreate struct {
	config
	mutation *UsageLogDetailMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsageLogID sets the "usage_log_id" field.
func (_c *UsageLogDetailCreate) SetUsageLogID(v int64) *UsageLogDetailCreate {
	_c.mutation.SetUsageLogID(v)
	return _c
}

// SetRequestPayloadJSON sets the "request_payload_json" field.
func (_c *UsageLogDetailCreate) SetRequestPayloadJSON(v string) *UsageLogDetailCreate {
	_c.mutation.SetRequestPayloadJSON(v)
	return _c
}

// SetNillableRequestPayloadJSON sets the "request_payload_json" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableRequestPayloadJSON(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetRequestPayloadJSON(*v)
	}
	return _c
}

// SetResponsePayloadJSON sets the "response_payload_json" field.
func (_c *UsageLogDetailCreate) SetResponsePayloadJSON(v string) *UsageLogDetailCreate {
	_c.mutation.SetResponsePayloadJSON(v)
	return _c
}

// SetNillableResponsePayloadJSON sets the "response_payload_json" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableResponsePayloadJSON(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetResponsePayloadJSON(*v)
	}
	return _c
}

// SetCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field.
func (_c *UsageLogDetailCreate) SetCompressedRequestPayloadJSON(v string) *UsageLogDetailCreate {
	_c.mutation.SetCompressedRequestPayloadJSON(v)
	return _c
}

// SetNillableCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableCompressedRequestPayloadJSON(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetCompressedRequestPayloadJSON(*v)
	}
	return _c
}

// SetCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field.
func (_c *UsageLogDetailCreate) SetCompressedResponsePayloadJSON(v string) *UsageLogDetailCreate {
	_c.mutation.SetCompressedResponsePayloadJSON(v)
	return _c
}

// SetNillableCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableCompressedResponsePayloadJSON(v *string) *UsageLogDetailCreate {
	if v != nil {
		_c.SetCompressedResponsePayloadJSON(*v)
	}
	return _c
}

// SetRequestPayloadBytes sets the "request_payload_bytes" field.
func (_c *UsageLogDetailCreate) SetRequestPayloadBytes(v int) *UsageLogDetailCreate {
	_c.mutation.SetRequestPayloadBytes(v)
	return _c
}

// SetNillableRequestPayloadBytes sets the "request_payload_bytes" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableRequestPayloadBytes(v *int) *UsageLogDetailCreate {
	if v != nil {
		_c.SetRequestPayloadBytes(*v)
	}
	return _c
}

// SetResponsePayloadBytes sets the "response_payload_bytes" field.
func (_c *UsageLogDetailCreate) SetResponsePayloadBytes(v int) *UsageLogDetailCreate {
	_c.mutation.SetResponsePayloadBytes(v)
	return _c
}

// SetNillableResponsePayloadBytes sets the "response_payload_bytes" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableResponsePayloadBytes(v *int) *UsageLogDetailCreate {
	if v != nil {
		_c.SetResponsePayloadBytes(*v)
	}
	return _c
}

// SetRequestTruncated sets the "request_truncated" field.
func (_c *UsageLogDetailCreate) SetRequestTruncated(v bool) *UsageLogDetailCreate {
	_c.mutation.SetRequestTruncated(v)
	return _c
}

// SetNillableRequestTruncated sets the "request_truncated" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableRequestTruncated(v *bool) *UsageLogDetailCreate {
	if v != nil {
		_c.SetRequestTruncated(*v)
	}
	return _c
}

// SetResponseTruncated sets the "response_truncated" field.
func (_c *UsageLogDetailCreate) SetResponseTruncated(v bool) *UsageLogDetailCreate {
	_c.mutation.SetResponseTruncated(v)
	return _c
}

// SetNillableResponseTruncated sets the "response_truncated" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableResponseTruncated(v *bool) *UsageLogDetailCreate {
	if v != nil {
		_c.SetResponseTruncated(*v)
	}
	return _c
}

// SetFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field.
func (_c *UsageLogDetailCreate) SetFullPayloadsCleanedAt(v time.Time) *UsageLogDetailCreate {
	_c.mutation.SetFullPayloadsCleanedAt(v)
	return _c
}

// SetNillableFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableFullPayloadsCleanedAt(v *time.Time) *UsageLogDetailCreate {
	if v != nil {
		_c.SetFullPayloadsCleanedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UsageLogDetailCreate) SetCreatedAt(v time.Time) *UsageLogDetailCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableCreatedAt(v *time.Time) *UsageLogDetailCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UsageLogDetailCreate) SetUpdatedAt(v time.Time) *UsageLogDetailCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UsageLogDetailCreate) SetNillableUpdatedAt(v *time.Time) *UsageLogDetailCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUsageLog sets the "usage_log" edge to the UsageLog entity.
func (_c *UsageLogDetailCreate) SetUsageLog(v *UsageLog) *UsageLogDetailCreate {
	return _c.SetUsageLogID(v.ID)
}

// Mutation returns the UsageLogDetailMutation object of the builder.
func (_c *UsageLogDetailCreate) Mutation() *UsageLogDetailMutation {
	return _c.mutation
}

// Save creates the UsageLogDetail in the database.
func (_c *UsageLogDetailCreate) Save(ctx context.Context) (*UsageLogDetail, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UsageLogDetailCreate) SaveX(ctx context.Context) *UsageLogDetail {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogDetailCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogDetailCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UsageLogDetailCreate) defaults() {
	if _, ok := _c.mutation.RequestTruncated(); !ok {
		v := usagelogdetail.DefaultRequestTruncated
		_c.mutation.SetRequestTruncated(v)
	}
	if _, ok := _c.mutation.ResponseTruncated(); !ok {
		v := usagelogdetail.DefaultResponseTruncated
		_c.mutation.SetResponseTruncated(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := usagelogdetail.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := usagelogdetail.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UsageLogDetailCreate) check() error {
	if _, ok := _c.mutation.UsageLogID(); !ok {
		return &ValidationError{Name: "usage_log_id", err: errors.New(`ent: missing required field "UsageLogDetail.usage_log_id"`)}
	}
	if _, ok := _c.mutation.RequestTruncated(); !ok {
		return &ValidationError{Name: "request_truncated", err: errors.New(`ent: missing required field "UsageLogDetail.request_truncated"`)}
	}
	if _, ok := _c.mutation.ResponseTruncated(); !ok {
		return &ValidationError{Name: "response_truncated", err: errors.New(`ent: missing required field "UsageLogDetail.response_truncated"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UsageLogDetail.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UsageLogDetail.updated_at"`)}
	}
	if len(_c.mutation.UsageLogIDs()) == 0 {
		return &ValidationError{Name: "usage_log", err: errors.New(`ent: missing required edge "UsageLogDetail.usage_log"`)}
	}
	return nil
}

func (_c *UsageLogDetailCreate) sqlSave(ctx context.Context) (*UsageLogDetail, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UsageLogDetailCreate) createSpec() (*UsageLogDetail, *sqlgraph.CreateSpec) {
	var (
		_node = &UsageLogDetail{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(usagelogdetail.Table, sqlgraph.NewFieldSpec(usagelogdetail.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestPayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldRequestPayloadJSON, field.TypeString, value)
		_node.RequestPayloadJSON = &value
	}
	if value, ok := _c.mutation.ResponsePayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldResponsePayloadJSON, field.TypeString, value)
		_node.ResponsePayloadJSON = &value
	}
	if value, ok := _c.mutation.CompressedRequestPayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldCompressedRequestPayloadJSON, field.TypeString, value)
		_node.CompressedRequestPayloadJSON = &value
	}
	if value, ok := _c.mutation.CompressedResponsePayloadJSON(); ok {
		_spec.SetField(usagelogdetail.FieldCompressedResponsePayloadJSON, field.TypeString, value)
		_node.CompressedResponsePayloadJSON = &value
	}
	if value, ok := _c.mutation.RequestPayloadBytes(); ok {
		_spec.SetField(usagelogdetail.FieldRequestPayloadBytes, field.TypeInt, value)
		_node.RequestPayloadBytes = &value
	}
	if value, ok := _c.mutation.ResponsePayloadBytes(); ok {
		_spec.SetField(usagelogdetail.FieldResponsePayloadBytes, field.TypeInt, value)
		_node.ResponsePayloadBytes = &value
	}
	if value, ok := _c.mutation.RequestTruncated(); ok {
		_spec.SetField(usagelogdetail.FieldRequestTruncated, field.TypeBool, value)
		_node.RequestTruncated = value
	}
	if value, ok := _c.mutation.ResponseTruncated(); ok {
		_spec.SetField(usagelogdetail.FieldResponseTruncated, field.TypeBool, value)
		_node.ResponseTruncated = value
	}
	if value, ok := _c.mutation.FullPayloadsCleanedAt(); ok {
		_spec.SetField(usagelogdetail.FieldFullPayloadsCleanedAt, field.TypeTime, value)
		_node.FullPayloadsCleanedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(usagelogdetail.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(usagelogdetail.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsageLogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   usagelogdetail.UsageLogTable,
			Columns: []string{usagelogdetail.UsageLogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UsageLogID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLogDetail.Create().
//		SetUsageLogID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogDetailUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogDetailCreate) OnConflict(opts ...sql.ConflictOption) *UsageLogDetailUpsertOne {
	_c.conflict = opts
	return &UsageLogDetailUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogDetailCreate) OnConflictColumns(columns ...string) *UsageLogDetailUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogDetailUpsertOne{
		create: _c,
	}
}

type (
	// UsageLogDetailUpsertOne is the builder for "upsert"-ing
	//  one UsageLogDetail node.
	UsageLogDetailUpsertOne struct {
		create *UsageLogDetailCreate
	}

	// UsageLogDetailUpsert is the "OnConflict" setter.
	UsageLogDetailUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogDetailUpsert) SetUsageLogID(v int64) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldUsageLogID, v)
	return u
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateUsageLogID() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldUsageLogID)
	return u
}

// SetRequestPayloadJSON sets the "request_payload_json" field.
func (u *UsageLogDetailUpsert) SetRequestPayloadJSON(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldRequestPayloadJSON, v)
	return u
}

// UpdateRequestPayloadJSON sets the "request_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateRequestPayloadJSON() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldRequestPayloadJSON)
	return u
}

// ClearRequestPayloadJSON clears the value of the "request_payload_json" field.
func (u *UsageLogDetailUpsert) ClearRequestPayloadJSON() *UsageLogDetailUpsert {
	u.SetNull(usagelogdetail.FieldRequestPayloadJSON)
	return u
}

// SetResponsePayloadJSON sets the "response_payload_json" field.
func (u *UsageLogDetailUpsert) SetResponsePayloadJSON(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldResponsePayloadJSON, v)
	return u
}

// UpdateResponsePayloadJSON sets the "response_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateResponsePayloadJSON() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldResponsePayloadJSON)
	return u
}

// ClearResponsePayloadJSON clears the value of the "response_payload_json" field.
func (u *UsageLogDetailUpsert) ClearResponsePayloadJSON() *UsageLogDetailUpsert {
	u.SetNull(usagelogdetail.FieldResponsePayloadJSON)
	return u
}

// SetCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field.
func (u *UsageLogDetailUpsert) SetCompressedRequestPayloadJSON(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldCompressedRequestPayloadJSON, v)
	return u
}

// UpdateCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateCompressedRequestPayloadJSON() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldCompressedRequestPayloadJSON)
	return u
}

// ClearCompressedRequestPayloadJSON clears the value of the "compressed_request_payload_json" field.
func (u *UsageLogDetailUpsert) ClearCompressedRequestPayloadJSON() *UsageLogDetailUpsert {
	u.SetNull(usagelogdetail.FieldCompressedRequestPayloadJSON)
	return u
}

// SetCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field.
func (u *UsageLogDetailUpsert) SetCompressedResponsePayloadJSON(v string) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldCompressedResponsePayloadJSON, v)
	return u
}

// UpdateCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateCompressedResponsePayloadJSON() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldCompressedResponsePayloadJSON)
	return u
}

// ClearCompressedResponsePayloadJSON clears the value of the "compressed_response_payload_json" field.
func (u *UsageLogDetailUpsert) ClearCompressedResponsePayloadJSON() *UsageLogDetailUpsert {
	u.SetNull(usagelogdetail.FieldCompressedResponsePayloadJSON)
	return u
}

// SetRequestPayloadBytes sets the "request_payload_bytes" field.
func (u *UsageLogDetailUpsert) SetRequestPayloadBytes(v int) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldRequestPayloadBytes, v)
	return u
}

// UpdateRequestPayloadBytes sets the "request_payload_bytes" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateRequestPayloadBytes() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldRequestPayloadBytes)
	return u
}

// AddRequestPayloadBytes adds v to the "request_payload_bytes" field.
func (u *UsageLogDetailUpsert) AddRequestPayloadBytes(v int) *UsageLogDetailUpsert {
	u.Add(usagelogdetail.FieldRequestPayloadBytes, v)
	return u
}

// ClearRequestPayloadBytes clears the value of the "request_payload_bytes" field.
func (u *UsageLogDetailUpsert) ClearRequestPayloadBytes() *UsageLogDetailUpsert {
	u.SetNull(usagelogdetail.FieldRequestPayloadBytes)
	return u
}

// SetResponsePayloadBytes sets the "response_payload_bytes" field.
func (u *UsageLogDetailUpsert) SetResponsePayloadBytes(v int) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldResponsePayloadBytes, v)
	return u
}

// UpdateResponsePayloadBytes sets the "response_payload_bytes" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateResponsePayloadBytes() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldResponsePayloadBytes)
	return u
}

// AddResponsePayloadBytes adds v to the "response_payload_bytes" field.
func (u *UsageLogDetailUpsert) AddResponsePayloadBytes(v int) *UsageLogDetailUpsert {
	u.Add(usagelogdetail.FieldResponsePayloadBytes, v)
	return u
}

// ClearResponsePayloadBytes clears the value of the "response_payload_bytes" field.
func (u *UsageLogDetailUpsert) ClearResponsePayloadBytes() *UsageLogDetailUpsert {
	u.SetNull(usagelogdetail.FieldResponsePayloadBytes)
	return u
}

// SetRequestTruncated sets the "request_truncated" field.
func (u *UsageLogDetailUpsert) SetRequestTruncated(v bool) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldRequestTruncated, v)
	return u
}

// UpdateRequestTruncated sets the "request_truncated" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateRequestTruncated() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldRequestTruncated)
	return u
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *UsageLogDetailUpsert) SetResponseTruncated(v bool) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldResponseTruncated, v)
	return u
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateResponseTruncated() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldResponseTruncated)
	return u
}

// SetFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field.
func (u *UsageLogDetailUpsert) SetFullPayloadsCleanedAt(v time.Time) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldFullPayloadsCleanedAt, v)
	return u
}

// UpdateFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateFullPayloadsCleanedAt() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldFullPayloadsCleanedAt)
	return u
}

// ClearFullPayloadsCleanedAt clears the value of the "full_payloads_cleaned_at" field.
func (u *UsageLogDetailUpsert) ClearFullPayloadsCleanedAt() *UsageLogDetailUpsert {
	u.SetNull(usagelogdetail.FieldFullPayloadsCleanedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageLogDetailUpsert) SetUpdatedAt(v time.Time) *UsageLogDetailUpsert {
	u.Set(usagelogdetail.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageLogDetailUpsert) UpdateUpdatedAt() *UsageLogDetailUpsert {
	u.SetExcluded(usagelogdetail.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogDetailUpsertOne) UpdateNewValues() *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(usagelogdetail.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UsageLogDetailUpsertOne) Ignore() *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogDetailUpsertOne) DoNothing() *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogDetailCreate.OnConflict
// documentation for more info.
func (u *UsageLogDetailUpsertOne) Update(set func(*UsageLogDetailUpsert)) *UsageLogDetailUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogDetailUpsertOne) SetUsageLogID(v int64) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateUsageLogID() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetRequestPayloadJSON sets the "request_payload_json" field.
func (u *UsageLogDetailUpsertOne) SetRequestPayloadJSON(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestPayloadJSON(v)
	})
}

// UpdateRequestPayloadJSON sets the "request_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateRequestPayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestPayloadJSON()
	})
}

// ClearRequestPayloadJSON clears the value of the "request_payload_json" field.
func (u *UsageLogDetailUpsertOne) ClearRequestPayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearRequestPayloadJSON()
	})
}

// SetResponsePayloadJSON sets the "response_payload_json" field.
func (u *UsageLogDetailUpsertOne) SetResponsePayloadJSON(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponsePayloadJSON(v)
	})
}

// UpdateResponsePayloadJSON sets the "response_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateResponsePayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponsePayloadJSON()
	})
}

// ClearResponsePayloadJSON clears the value of the "response_payload_json" field.
func (u *UsageLogDetailUpsertOne) ClearResponsePayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearResponsePayloadJSON()
	})
}

// SetCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field.
func (u *UsageLogDetailUpsertOne) SetCompressedRequestPayloadJSON(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetCompressedRequestPayloadJSON(v)
	})
}

// UpdateCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateCompressedRequestPayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateCompressedRequestPayloadJSON()
	})
}

// ClearCompressedRequestPayloadJSON clears the value of the "compressed_request_payload_json" field.
func (u *UsageLogDetailUpsertOne) ClearCompressedRequestPayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearCompressedRequestPayloadJSON()
	})
}

// SetCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field.
func (u *UsageLogDetailUpsertOne) SetCompressedResponsePayloadJSON(v string) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetCompressedResponsePayloadJSON(v)
	})
}

// UpdateCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateCompressedResponsePayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateCompressedResponsePayloadJSON()
	})
}

// ClearCompressedResponsePayloadJSON clears the value of the "compressed_response_payload_json" field.
func (u *UsageLogDetailUpsertOne) ClearCompressedResponsePayloadJSON() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearCompressedResponsePayloadJSON()
	})
}

// SetRequestPayloadBytes sets the "request_payload_bytes" field.
func (u *UsageLogDetailUpsertOne) SetRequestPayloadBytes(v int) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestPayloadBytes(v)
	})
}

// AddRequestPayloadBytes adds v to the "request_payload_bytes" field.
func (u *UsageLogDetailUpsertOne) AddRequestPayloadBytes(v int) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.AddRequestPayloadBytes(v)
	})
}

// UpdateRequestPayloadBytes sets the "request_payload_bytes" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateRequestPayloadBytes() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestPayloadBytes()
	})
}

// ClearRequestPayloadBytes clears the value of the "request_payload_bytes" field.
func (u *UsageLogDetailUpsertOne) ClearRequestPayloadBytes() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearRequestPayloadBytes()
	})
}

// SetResponsePayloadBytes sets the "response_payload_bytes" field.
func (u *UsageLogDetailUpsertOne) SetResponsePayloadBytes(v int) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponsePayloadBytes(v)
	})
}

// AddResponsePayloadBytes adds v to the "response_payload_bytes" field.
func (u *UsageLogDetailUpsertOne) AddResponsePayloadBytes(v int) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.AddResponsePayloadBytes(v)
	})
}

// UpdateResponsePayloadBytes sets the "response_payload_bytes" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateResponsePayloadBytes() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponsePayloadBytes()
	})
}

// ClearResponsePayloadBytes clears the value of the "response_payload_bytes" field.
func (u *UsageLogDetailUpsertOne) ClearResponsePayloadBytes() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearResponsePayloadBytes()
	})
}

// SetRequestTruncated sets the "request_truncated" field.
func (u *UsageLogDetailUpsertOne) SetRequestTruncated(v bool) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestTruncated(v)
	})
}

// UpdateRequestTruncated sets the "request_truncated" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateRequestTruncated() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestTruncated()
	})
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *UsageLogDetailUpsertOne) SetResponseTruncated(v bool) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponseTruncated(v)
	})
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateResponseTruncated() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponseTruncated()
	})
}

// SetFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field.
func (u *UsageLogDetailUpsertOne) SetFullPayloadsCleanedAt(v time.Time) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetFullPayloadsCleanedAt(v)
	})
}

// UpdateFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateFullPayloadsCleanedAt() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateFullPayloadsCleanedAt()
	})
}

// ClearFullPayloadsCleanedAt clears the value of the "full_payloads_cleaned_at" field.
func (u *UsageLogDetailUpsertOne) ClearFullPayloadsCleanedAt() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearFullPayloadsCleanedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageLogDetailUpsertOne) SetUpdatedAt(v time.Time) *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageLogDetailUpsertOne) UpdateUpdatedAt() *UsageLogDetailUpsertOne {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UsageLogDetailUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogDetailCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogDetailUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UsageLogDetailUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UsageLogDetailUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UsageLogDetailCreateBulk is the builder for creating many UsageLogDetail entities in bulk.
type UsageLogDetailCreateBulk struct {
	config
	err      error
	builders []*UsageLogDetailCreate
	conflict []sql.ConflictOption
}

// Save creates the UsageLogDetail entities in the database.
func (_c *UsageLogDetailCreateBulk) Save(ctx context.Context) ([]*UsageLogDetail, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UsageLogDetail, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsageLogDetailMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UsageLogDetailCreateBulk) SaveX(ctx context.Context) []*UsageLogDetail {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UsageLogDetailCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UsageLogDetailCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UsageLogDetail.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UsageLogDetailUpsert) {
//			SetUsageLogID(v+v).
//		}).
//		Exec(ctx)
func (_c *UsageLogDetailCreateBulk) OnConflict(opts ...sql.ConflictOption) *UsageLogDetailUpsertBulk {
	_c.conflict = opts
	return &UsageLogDetailUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UsageLogDetailCreateBulk) OnConflictColumns(columns ...string) *UsageLogDetailUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UsageLogDetailUpsertBulk{
		create: _c,
	}
}

// UsageLogDetailUpsertBulk is the builder for "upsert"-ing
// a bulk of UsageLogDetail nodes.
type UsageLogDetailUpsertBulk struct {
	create *UsageLogDetailCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UsageLogDetailUpsertBulk) UpdateNewValues() *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(usagelogdetail.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UsageLogDetail.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UsageLogDetailUpsertBulk) Ignore() *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UsageLogDetailUpsertBulk) DoNothing() *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UsageLogDetailCreateBulk.OnConflict
// documentation for more info.
func (u *UsageLogDetailUpsertBulk) Update(set func(*UsageLogDetailUpsert)) *UsageLogDetailUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UsageLogDetailUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsageLogID sets the "usage_log_id" field.
func (u *UsageLogDetailUpsertBulk) SetUsageLogID(v int64) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUsageLogID(v)
	})
}

// UpdateUsageLogID sets the "usage_log_id" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateUsageLogID() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUsageLogID()
	})
}

// SetRequestPayloadJSON sets the "request_payload_json" field.
func (u *UsageLogDetailUpsertBulk) SetRequestPayloadJSON(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestPayloadJSON(v)
	})
}

// UpdateRequestPayloadJSON sets the "request_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateRequestPayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestPayloadJSON()
	})
}

// ClearRequestPayloadJSON clears the value of the "request_payload_json" field.
func (u *UsageLogDetailUpsertBulk) ClearRequestPayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearRequestPayloadJSON()
	})
}

// SetResponsePayloadJSON sets the "response_payload_json" field.
func (u *UsageLogDetailUpsertBulk) SetResponsePayloadJSON(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponsePayloadJSON(v)
	})
}

// UpdateResponsePayloadJSON sets the "response_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateResponsePayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponsePayloadJSON()
	})
}

// ClearResponsePayloadJSON clears the value of the "response_payload_json" field.
func (u *UsageLogDetailUpsertBulk) ClearResponsePayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearResponsePayloadJSON()
	})
}

// SetCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field.
func (u *UsageLogDetailUpsertBulk) SetCompressedRequestPayloadJSON(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetCompressedRequestPayloadJSON(v)
	})
}

// UpdateCompressedRequestPayloadJSON sets the "compressed_request_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateCompressedRequestPayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateCompressedRequestPayloadJSON()
	})
}

// ClearCompressedRequestPayloadJSON clears the value of the "compressed_request_payload_json" field.
func (u *UsageLogDetailUpsertBulk) ClearCompressedRequestPayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearCompressedRequestPayloadJSON()
	})
}

// SetCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field.
func (u *UsageLogDetailUpsertBulk) SetCompressedResponsePayloadJSON(v string) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetCompressedResponsePayloadJSON(v)
	})
}

// UpdateCompressedResponsePayloadJSON sets the "compressed_response_payload_json" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateCompressedResponsePayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateCompressedResponsePayloadJSON()
	})
}

// ClearCompressedResponsePayloadJSON clears the value of the "compressed_response_payload_json" field.
func (u *UsageLogDetailUpsertBulk) ClearCompressedResponsePayloadJSON() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearCompressedResponsePayloadJSON()
	})
}

// SetRequestPayloadBytes sets the "request_payload_bytes" field.
func (u *UsageLogDetailUpsertBulk) SetRequestPayloadBytes(v int) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestPayloadBytes(v)
	})
}

// AddRequestPayloadBytes adds v to the "request_payload_bytes" field.
func (u *UsageLogDetailUpsertBulk) AddRequestPayloadBytes(v int) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.AddRequestPayloadBytes(v)
	})
}

// UpdateRequestPayloadBytes sets the "request_payload_bytes" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateRequestPayloadBytes() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestPayloadBytes()
	})
}

// ClearRequestPayloadBytes clears the value of the "request_payload_bytes" field.
func (u *UsageLogDetailUpsertBulk) ClearRequestPayloadBytes() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearRequestPayloadBytes()
	})
}

// SetResponsePayloadBytes sets the "response_payload_bytes" field.
func (u *UsageLogDetailUpsertBulk) SetResponsePayloadBytes(v int) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponsePayloadBytes(v)
	})
}

// AddResponsePayloadBytes adds v to the "response_payload_bytes" field.
func (u *UsageLogDetailUpsertBulk) AddResponsePayloadBytes(v int) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.AddResponsePayloadBytes(v)
	})
}

// UpdateResponsePayloadBytes sets the "response_payload_bytes" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateResponsePayloadBytes() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponsePayloadBytes()
	})
}

// ClearResponsePayloadBytes clears the value of the "response_payload_bytes" field.
func (u *UsageLogDetailUpsertBulk) ClearResponsePayloadBytes() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearResponsePayloadBytes()
	})
}

// SetRequestTruncated sets the "request_truncated" field.
func (u *UsageLogDetailUpsertBulk) SetRequestTruncated(v bool) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetRequestTruncated(v)
	})
}

// UpdateRequestTruncated sets the "request_truncated" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateRequestTruncated() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateRequestTruncated()
	})
}

// SetResponseTruncated sets the "response_truncated" field.
func (u *UsageLogDetailUpsertBulk) SetResponseTruncated(v bool) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetResponseTruncated(v)
	})
}

// UpdateResponseTruncated sets the "response_truncated" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateResponseTruncated() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateResponseTruncated()
	})
}

// SetFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field.
func (u *UsageLogDetailUpsertBulk) SetFullPayloadsCleanedAt(v time.Time) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetFullPayloadsCleanedAt(v)
	})
}

// UpdateFullPayloadsCleanedAt sets the "full_payloads_cleaned_at" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateFullPayloadsCleanedAt() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateFullPayloadsCleanedAt()
	})
}

// ClearFullPayloadsCleanedAt clears the value of the "full_payloads_cleaned_at" field.
func (u *UsageLogDetailUpsertBulk) ClearFullPayloadsCleanedAt() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.ClearFullPayloadsCleanedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UsageLogDetailUpsertBulk) SetUpdatedAt(v time.Time) *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UsageLogDetailUpsertBulk) UpdateUpdatedAt() *UsageLogDetailUpsertBulk {
	return u.Update(func(s *UsageLogDetailUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *UsageLogDetailUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UsageLogDetailCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UsageLogDetailCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UsageLogDetailUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
