// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/usagelogdetail"
)

// UsageLogDetail is the model entity for the UsageLogDetail schema.
type UsageLogDetail struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UsageLogID holds the value of the "usage_log_id" field.
	UsageLogID int64 `json:"usage_log_id,omitempty"`
	// RequestPayloadJSON holds the value of the "request_payload_json" field.
	RequestPayloadJSON *string `json:"request_payload_json,omitempty"`
	// ResponsePayloadJSON holds the value of the "response_payload_json" field.
	ResponsePayloadJSON *string `json:"response_payload_json,omitempty"`
	// RequestPayloadBytes holds the value of the "request_payload_bytes" field.
	RequestPayloadBytes *int `json:"request_payload_bytes,omitempty"`
	// ResponsePayloadBytes holds the value of the "response_payload_bytes" field.
	ResponsePayloadBytes *int `json:"response_payload_bytes,omitempty"`
	// RequestTruncated holds the value of the "request_truncated" field.
	RequestTruncated bool `json:"request_truncated,omitempty"`
	// ResponseTruncated holds the value of the "response_truncated" field.
	ResponseTruncated bool `json:"response_truncated,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsageLogDetailQuery when eager-loading is set.
	Edges        UsageLogDetailEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsageLogDetailEdges holds the relations/edges for other nodes in the graph.
type UsageLogDetailEdges struct {
	// UsageLog holds the value of the usage_log edge.
	UsageLog *UsageLog `json:"usage_log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsageLogOrErr returns the UsageLog value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsageLogDetailEdges) UsageLogOrErr() (*UsageLog, error) {
	if e.UsageLog != nil {
		return e.UsageLog, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: usagelog.Label}
	}
	return nil, &NotLoadedError{edge: "usage_log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsageLogDetail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usagelogdetail.FieldRequestTruncated, usagelogdetail.FieldResponseTruncated:
			values[i] = new(sql.NullBool)
		case usagelogdetail.FieldID, usagelogdetail.FieldUsageLogID, usagelogdetail.FieldRequestPayloadBytes, usagelogdetail.FieldResponsePayloadBytes:
			values[i] = new(sql.NullInt64)
		case usagelogdetail.FieldRequestPayloadJSON, usagelogdetail.FieldResponsePayloadJSON:
			values[i] = new(sql.NullString)
		case usagelogdetail.FieldCreatedAt, usagelogdetail.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsageLogDetail fields.
func (_m *UsageLogDetail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usagelogdetail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case usagelogdetail.FieldUsageLogID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_log_id", values[i])
			} else if value.Valid {
				_m.UsageLogID = value.Int64
			}
		case usagelogdetail.FieldRequestPayloadJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload_json", values[i])
			} else if value.Valid {
				_m.RequestPayloadJSON = new(string)
				*_m.RequestPayloadJSON = value.String
			}
		case usagelogdetail.FieldResponsePayloadJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field response_payload_json", values[i])
			} else if value.Valid {
				_m.ResponsePayloadJSON = new(string)
				*_m.ResponsePayloadJSON = value.String
			}
		case usagelogdetail.FieldRequestPayloadBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field request_payload_bytes", values[i])
			} else if value.Valid {
				_m.RequestPayloadBytes = new(int)
				*_m.RequestPayloadBytes = int(value.Int64)
			}
		case usagelogdetail.FieldResponsePayloadBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_payload_bytes", values[i])
			} else if value.Valid {
				_m.ResponsePayloadBytes = new(int)
				*_m.ResponsePayloadBytes = int(value.Int64)
			}
		case usagelogdetail.FieldRequestTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field request_truncated", values[i])
			} else if value.Valid {
				_m.RequestTruncated = value.Bool
			}
		case usagelogdetail.FieldResponseTruncated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field response_truncated", values[i])
			} else if value.Valid {
				_m.ResponseTruncated = value.Bool
			}
		case usagelogdetail.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case usagelogdetail.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsageLogDetail.
// This includes values selected through modifiers, order, etc.
func (_m *UsageLogDetail) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsageLog queries the "usage_log" edge of the UsageLogDetail entity.
func (_m *UsageLogDetail) QueryUsageLog() *UsageLogQuery {
	return NewUsageLogDetailClient(_m.config).QueryUsageLog(_m)
}

// Update returns a builder for updating this UsageLogDetail.
// Note that you need to call UsageLogDetail.Unwrap() before calling this method if this UsageLogDetail
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UsageLogDetail) Update() *UsageLogDetailUpdateOne {
	return NewUsageLogDetailClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UsageLogDetail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UsageLogDetail) Unwrap() *UsageLogDetail {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsageLogDetail is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UsageLogDetail) String() string {
	var builder strings.Builder
	builder.WriteString("UsageLogDetail(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("usage_log_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsageLogID))
	builder.WriteString(", ")
	if v := _m.RequestPayloadJSON; v != nil {
		builder.WriteString("request_payload_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResponsePayloadJSON; v != nil {
		builder.WriteString("response_payload_json=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.RequestPayloadBytes; v != nil {
		builder.WriteString("request_payload_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ResponsePayloadBytes; v != nil {
		builder.WriteString("response_payload_bytes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("request_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestTruncated))
	builder.WriteString(", ")
	builder.WriteString("response_truncated=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResponseTruncated))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UsageLogDetails is a parsable slice of UsageLogDetail.
type UsageLogDetails []*UsageLogDetail
